---
aws:
    type: dict
    required: True
    allow_unknown: False
    empty: False
    schema:
        region:
            type: string
            allowed:
                - us-east-1
                - us-east-2
                - us-west-1
                - us-west-2
                - ap-east-1
                - ap-south-1
                - ap-northeast-1
                - ap-northeast-2
                - ap-northeast-3
                - ap-southeast-1
                - ap-southeast-2
                - ca-central-1
                - cn-north-1
                - cn-northwest-1
                - eu-central-1
                - eu-west-1
                - eu-west-2
                - eu-west-3
                - eu-north-1
                - me-south-1
                - sa-east-1
                - us-gov-east-1
                - us-gov-west-1

main:
    type: dict
    required: True
    allow_unknown: False
    empty: False
    schema:
        stack_name:
            type: string

show_log_on_failure_only:
    type: boolean
    required: True

poll_timeout:
    type: dict
    required: True
    allow_unknown: False
    empty: False
    schema:
        check_command_execution:
            type: dict
            required: True
            allow_unknown: False
            empty: False
            schema:
                retries:
                    type: integer
                delay:
                    type: integer
